---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myservice
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  chart:
    git: git@github.com:3lvia/kubernetes-charts
    ref: master
    path: elvia-deployment
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.4
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
